version: '3' #docker-compose file format version
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always # restart container when failed (always, on-failure, "no", unless-stopped) # 
    build: . #look in the current dir for a docker file and build this container
    ports:
      - "4001:8081" # "-"" specifies an array

# docker-compose up 
# docker-compose up --build #rebuild 
# docker-compose down
# docker-compose ps 