# docker build -f Dockerfile.env -t automated-image:1.1 .
# sudo docker run -it --rm -p 5000:5000 automated-image:1.1


FROM python 
WORKDIR /app
COPY hello.py .  
RUN pip install Flask
ENV FLASK_APP="hello"
ENV FLASK_ENV="development"
ENV FLASK_RUN_HOST="0.0.0.0"
ENV FLASK_RUN_PORT="5000"
CMD ["flask", "run"]

